stages:
  - pre_commit
  - build

default:
  interruptible: true

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - when: never

variables:
  GIT_SUBMODULE_STRATEGY: none
  IDF_CCACHE_ENABLE: "1"
  CCACHE_NOHASHDIR: "1"
  CCACHE_SLOPPINESS: "locale,time_macros,random_seed"
  IDF_PATH: "$CI_PROJECT_DIR/esp-idf"
