stages:
  - deploy

default:
  interruptible: true

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never

    - if: '$CI_COMMIT_BRANCH == "main"'
      auto_cancel:
        on_new_commit: none

    - when: always
      auto_cancel:
        on_new_commit: interruptible
